### ISSUE TITLE
feature: Container orchestration with dae-wing

### ISSUE THREAD

**Issue by hero-intelligent** [daeuniverse/daed-revived-next#29]
Dockerfile:

```Dockerfile
# can't build on latest node version v21.0.0, because of this issue:
# https://github.com/nodejs/node/issues/50269
# neither on bun, because of this issue:
# https://github.com/oven-sh/bun/issues/4671
FROM docker.io/node:20-alpine AS base

FROM base AS builder

WORKDIR /build

COPY . .

ENV HUSKY 0
ENV STANDALONE 1

RUN corepack enable
RUN corepack prepare pnpm@latest --activate

RUN pnpm install
RUN pnpm build

FROM golang:1.21-bookworm as wing

RUN \
    apt-get update; apt-get install -y git make llvm-15 clang-15; \
    apt-get clean autoclean && apt-get autoremove -y && rm -rf /var/lib/{apt,dpkg,cache,log}/

# build bundle process
ENV CGO_ENABLED=0
ENV CLANG=clang-15

WORKDIR /build/wing

COPY ./wing .

RUN make deps
RUN go build -o dae-wing

FROM base AS runner

WORKDIR /app

COPY --from=builder /build/public ./public

RUN mkdir .next

COPY --from=builder /build/.next/standalone .
COPY --from=builder /build/.next/static ./.next/static

ENV NODE_ENV production

COPY --from=wing /build/wing/dae-wing /usr/local/bin

EXPOSE 3000

CMD dae-wing run -c ./etc/dae-wing --api-only & node server.js
```

```sh
sudo docker run -it \
    --privileged \
    --network=host \
    --pid=host \
    --restart=always \
    -v /sys:/sys \
    -v /etc/daed:/etc/dae-wing \
    --name=daed-next \
    next
```

**Comment by kunish** [comment]
> I have some questions.
> 
> 1. why the dashboard site is at `127.0.1.1` instead of `127.0.0.1` or `0.0.0.0`?
> 
> related log:
> 
> ```
>   ▲ Next.js 13.5.6
>   - Local:        http://debian:3000
>   - Network:      http://127.0.1.1:3000
> 
>  ✓ Ready in 41ms
> ```
> 
> 2. Why the `too weak password` is not displayed onto the screen instead of connection status `500`?
> 
> ```
>  ⨯ ClientError: too weak password; should contain numbers and letters, and no less than 6 in length: {"response":{"errors":[{"message":"too weak password; should contain numbers and letters, and no less than 6 in length","path":["createUser"]}],"data":null,"status":200,"headers":{}},"request":{"query":"mutation CreateUser($username: String!, $password: String!) {\n  createUser(username: $username, password: $password)\n}","variables":{"username":"daed","password":"daeuniverse"}}}
>     at makeRequest (/app/.next/server/chunks/871.js:120:169752)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async POST (/app/.next/server/app/api/login/route.js:27:37)
>     at async /app/node_modules/.pnpm/next@13.5.6_@babel+core@7.23.2_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:14:39709 {
>   response: {
>     errors: [ [Object] ],
>     data: null,
>     status: 200,
>     headers: Headers { [Symbol(map)]: [Object: null prototype] }
>   },
>   request: {
>     query: 'mutation CreateUser($username: String!, $password: String!) {\n' +
>       '  createUser(username: $username, password: $password)\n' +
>       '}',
>     variables: { username: 'daed', password: 'daeuniverse' }
>   }
> }
> WARN[0156] dangerous converting: may exceeds graphQL int32 range  name=SoMarkFromDae type=uint32
> WARN[0156] dangerous converting: may exceeds graphQL int32 range  name=SoMarkFromDae type=uint32
> ^CERRO[0196] Exiting: interrupt   
> ```
> 
> 3. At the start of the program and trying to access the dashboard, I get a white screen with a blue spinner in the middle, with a notice from browser read `Performing a TLS Handshake to cdn.jsdelivr.net...`, until I click on the cancel refresh button.

Haven't done too much error handling or forwarding yet

**Comment by kunish** [comment]
By the way, personaly, i really dont like the **&** business

**Comment by kunish** [comment]
What i mean was something like this

```Dockerfile
# wing/Dockerfile
```

```yaml
# docker-compose.yml
version: '3'

services:
  dae-wing:
    # referencing the wing/Dockerfile inside the dae-wing submodule directory
    build: wing
    container_name: dae-wing
    ports:
      - '2023:2023'

  daed:
    # referencing the Dockerfile at the root directory of this repository
    build: .
    container_name: daed
    environment:
      WING_API_URL: 'http://dae-wing:2023'
    ports:
      - '3000:3000'
    depends_on:
      - dae-wing
```
